mode: 'async' 
# available modes are:
# sync, async, mixed
#
# Logging
LOG_LEVEL_CONSOLE: 'info'
LOG_LEVEL_FILE: 'debug'
LOG_LEVEL: 'info'
LOG_FILE_PATH: 'chaos.log'
total_time: 2
teardown_vms: True

# vshpere 
vcenter_host: "x.qa.suse.cz"
vcenter_user: "administrator@vsphere.local"
vcenter_password: "O!dHacker5"
dc_name: "Datacenter"
cluster_name: "clusteroony"
esxi_hosts: {"kratos.qa.suse.cz": ['root', 'O!dHacker5'],
             "momus.qa.suse.cz": ['root', 'O!dHacker5'],
             "zelus.qa.suse.cz": ['root', 'O!dHacker5']
            }
template_vm_name: "windows_template"

# Ceph Admin
ceph_adm_node: "hornet.qam.suse.cz"
ceph_adm_user: "root"
ceph_adm_password: "susetesting"

# Gateways
gateways: {"bee.qam.suse.cz": ["root", "susetesting"],
           "fly.qam.suse.cz": ["root", "susetesting"]
          }
#gateway_user: "root"
#gateway_password: "susetesting"
ds_names: ["cephtest1", "cephtest2"]

# General settings
filter_string: "ceph_"
max_vms: 4
max_tasks: 10
wait_for_health_ok_t: 360
force_reboot: False
max_down_osds_ratio: 0.2
MAX_DEPTH: 15
chaos_rate: 500
#ceph_health_is_ok_with: 'HEALTH_WARN'
ceph_health_is_ok_with: 'HEALTH_OK'
